import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/splash">Splash</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/typeform">Typeform</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/welcome">Welcome</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/emailresetpasswordlink">EmailResetPasswordLink</Link>
        </li>
        <li>
          <Link to="/generatingresume">GeneratingResume</Link>
        </li>
        <li>
          <Link to="/settings">Settings</Link>
        </li>
        <li>
          <Link to="/emailverification">EmailVerification</Link>
        </li>
        <li>
          <Link to="/createnewpassword">CreateNewPassword</Link>
        </li>
        <li>
          <Link to="/generatedresume">GeneratedResume</Link>
        </li>
        <li>
          <Link to="/accountsettings">AccountSettings</Link>
        </li>
        <li>
          <Link to="/verificationcode">VerificationCode</Link>
        </li>
        <li>
          <Link to="/passwordresetconfirmation">PasswordResetConfirmation</Link>
        </li>
        <li>
          <Link to="/deleteaccount">DeleteAccount</Link>
        </li>
        <li>
          <Link to="/changepassword">ChangePassword</Link>
        </li>
        <li>
          <Link to="/profile">Profile</Link>
        </li>
        <li>
          <Link to="/passwordreset">PasswordReset</Link>
        </li>
        <li>
          <Link to="/updateresume">UpdateResume</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
